USE [master]
GO

/****** Object:  Database [ChicagoBikeData]    Script Date: 13/11/2021 14:46:32 ******/
CREATE DATABASE [ChicagoBikeData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ChicagoBikeData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ChicagoBikeData.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ChicagoBikeData_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ChicagoBikeData_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ChicagoBikeData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ChicagoBikeData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET ARITHABORT OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ChicagoBikeData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ChicagoBikeData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ChicagoBikeData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ChicagoBikeData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET RECOVERY FULL 
GO

ALTER DATABASE [ChicagoBikeData] SET  MULTI_USER 
GO

ALTER DATABASE [ChicagoBikeData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ChicagoBikeData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ChicagoBikeData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ChicagoBikeData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ChicagoBikeData] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ChicagoBikeData] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ChicagoBikeData] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ChicagoBikeData] SET  READ_WRITE 
GO


